[Distribution]
Distribution=debian
Release=trixie

[Content]
#Packages=linux-image-amd64,systemd-boot-efi,systemd-resolved,login,passwd,expect,dbus-user-session,forticlient,iproute2,sudo # DEBUG
Packages=linux-image-amd64,systemd-boot-efi,systemd-resolved,login,passwd,expect,dbus-user-session,forticlient,iproute2
Bootable=true
Bootloader=uki

[Output]
OutputDirectory=build

[Runtime]
RuntimeNetwork=none
QemuArgs=-nic user,model=virtio-net-pci,hostfwd=tcp:0.0.0.0:3389-:3389 -snapshot
